server:
  port: 8090

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      default-filters:
        - name: AuthenticationFilter
      routes:
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/auth/**

        - id: customer-service
          uri: lb://customer-service
          predicates:
            - Path=/customer/**

        - id: business-service
          uri: lb://business-service
          predicates:
            - Path=/business/**

        - id: inventory-service
          uri: lb://inventory-service
          predicates:
            - Path=/inventory/**

        - id: reports-service
          uri: lb:ws://reports-service
          predicates:
            - Path=/reports-ws/**

jwt:
  secret: ${JWT_SECRET:SakilaSecretKeyForJWTAuthSystemMicroservicesProfessionalCode2026}

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka/}
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}
    ip-address: 127.0.0.1

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    disable-swagger-default-url: true
    urls:
      - name: Auth Service
        url: /auth/v3/api-docs
      - name: Customer Service
        url: /customer/v3/api-docs